/// <reference types = "cypress" />
import faker from 'faker'
describe('Registration', () => {
  const email = faker.internet.email()
  it('Randomowy emial', () => {
      cy.visit('http://automationpractice.com/index.php')
      cy.get('.login').click()
      cy.get('input[name=email_create]').type(email)
      cy.get('#SubmitCreate > span').click()
      cy.get('#id_gender1').click()
      cy.get('#customer_firstname').type('Kamil')
      cy.get('#customer_lastname').type('Labedzki')
      cy.get('#passwd').type('1234567')
      cy.get("#days").select('2')
      cy.get('#months').select('2')
      cy.get('#years').select('1977')
      cy.get('#company').type('dasdasfasd')
      cy.get('#address1').type('asfaisjs')
      cy.get('#address2').type('asdfgasdg')
      cy.get('#city').type('asdfsg')
      cy.get('#id_state').select('5')
      cy.get('#postcode').type('12345')
      cy.get('#phone').type('123456789')
      cy.get('#phone_mobile').type('123456789')
      cy.get('#submitAccount > span').click()
  })
  it('logowanie i powrót na strone główna', () => {
      cy.visit('http://automationpractice.com/index.php')
      cy.get('.login').click()
      cy.get('#email').type(email)
      cy.get('#passwd').type('1234567')
      cy.get('#SubmitLogin > span').click()
      cy.get('.logo').click()
  })
  it('Dodawanie i płatność', () => {
    cy.get('.sf-menu > :nth-child(3) > a').click()
    cy.get('.product_img_link > .replace-2x').trigger('mouseover')
    cy.get("Add to cart").click()
    cy.get('Submit').click()
    cy.get('.exclusive > span').click()
    cy.get('.button-medium > span').click()
        cy.get('.cart_navigation > .button > span').click()
        cy.get('.cart_navigation > .button > span').click()
        cy.get('#cgv').click()
        cy.get('.cart_navigation > .button > span').click()
        cy.get('.bankwire').click()
        cy.get('#cart_navigation > .button > span').click()
        cy.get('.logo').click()
  })
    it('Dodawanie i odejmowanie produktw', () => {
      cy.get('.logo').click()
        cy.get('.sf-menu > :nth-child(2) > .sf-with-ul').click()
        cy.get(':nth-child(2) > .subcategory-image > .img').click()
        cy.get('.product_img_link > .replace-2x').click()
        cy.get('add_to_cart').click()
        cy.get('.button-medium > span').click()
        cy.get('Continue shopping').click()
        cy.get('[id="quantity_wanted"]').clear().type(3)
        cy.get('group_1').click().type('m')
        cy.get('.logo').click()
      })
  it('dodawanie sukienki przecenionej do listy życzeń',() =>{
    cy.get('.logo').click()
    cy.get('#homefeatured > .first-in-line.last-line > .product-container > .left-block > .product-image-container > .product_img_link > .replace-2x').click()
    cy.get('#wishlist_button').click()
    cy.get('.fancybox-item').click()
   })
})


